# Generated by Django 2.2.5 on 2021-04-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210413_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genter',
            new_name='gender',
        ),
    ]
